export const wilayahBesar = [
  "Hokkaidō", "Tohoku", "Tokyo", "Chubu", "Hokuriku",
  "Kansai", "Chugoku", "Shikoku", "Kyusyu", "Okinawa"
];

export const mapping: Record<string, string> = {
  "Hokkaidō": "Hokkaidō",
  "Aomori": "Tohoku",
  "Iwate": "Tohoku",
  "Miyagi": "Tohoku",
  "Akita": "Tohoku",
  "Yamagata": "Tohoku",
  "Fukushima": "Tohoku",
  "Tokyo": "Tokyo",
  "Chiba": "Tokyo",
  "Kanagawa": "Tokyo",
  "Saitama": "Tokyo",
  "Yamanashi": "Chubu",
  "Nagano": "Chubu",
  "Shizuoka": "Chubu",
  "Aichi": "Chubu",
  "Toyama": "Hokuriku",
  "Ishikawa": "Hokuriku",
  "Fukui": "Hokuriku",
  "Osaka": "Kansai",
  "Kyoto": "Kansai",
  "Hyogo": "Kansai",
  "Nara": "Kansai",
  "Wakayama": "Kansai",
  "Shiga": "Kansai",
  "Hiroshima": "Chugoku",
  "Okayama": "Chugoku",
  "Yamaguchi": "Chugoku",
  "Shimane": "Chugoku",
  "Tottori": "Chugoku",
  "Kagawa": "Shikoku",
  "Tokushima": "Shikoku",
  "Ehime": "Shikoku",
  "Kochi": "Shikoku",
  "Fukuoka": "Kyusyu",
  "Saga": "Kyusyu",
  "Nagasaki": "Kyusyu",
  "Kumamoto": "Kyusyu",
  "Oita": "Kyusyu",
  "Miyazaki": "Kyusyu",
  "Kagoshima": "Kyusyu",
  "Okinawa": "Okinawa"
};
